Update mail.php
wordplate/mail pull request #2
Opened 2017-03-12 15:50 UTC by ihsanberahim

SMTP Error: Could not authenticate. (fixed)
* it works with mailcatcher too by simply set MAIL_HOST=127.0.0.1 and set MAIL_PORT=1025

2017-03-12 17:48 UTC, vinkla commented
What is the use case here? If there are no credentials you can simply not use this plugin?

2017-03-12 18:15 UTC, ihsanberahim commented
this plugin require to enable SMTP. 

Mailcatcher don't have and don't need Auth. We can leave username and password as null.
The update i made suite more than 1 situation automatically. If developer set the username and password, for sure they needs SMTPAuth otherwise SMTP should know that if there are no credential for sure we SMTPAuth should be disabled.

2017-03-12 18:17 UTC, vinkla commented
In that case you can use the default setting and not use this plugin. Right?

2017-03-12 18:19 UTC, ihsanberahim commented
in wordpress no SMTP setting by default. Just the main issue here is this plugin hardcoded SMTPAuth enabled.

You can try use mailcatcher then you will see why i request this pull.

2017-03-13 09:17 UTC, vinkla requested changes
Please see my review comments.

2017-03-13 09:17 UTC, vinkla commented on mail.php
> +    $mail->SMTPAuth = (!empty($username) && !empty($password));
Update this line to the following;

```php
$mail->SMTPAuth = env('MAIL_USERNAME') && env('MAIL_PASSWORD');
```

Then please test it.

2017-03-13 09:30 UTC, ihsanberahim reviewed
tested. it works.

2017-03-13 09:30 UTC, ihsanberahim commented on mail.php
> +    $mail->SMTPAuth = (!empty($username) && !empty($password));
done

2017-03-13 18:16 UTC, vinkla requested changes
Please see my new comment.

2017-03-13 18:16 UTC, vinkla commented on mail.php
> +    $mail->IsSMTP();
@ihsanberahim why did you move this here?

2017-03-14 00:03 UTC, ihsanberahim reviewed
Put back IsSMTP where it placed before.

2017-03-14 08:54 UTC, vinkla approved these changes

2017-03-14 08:54 UTC, merged

2017-03-14 08:54 UTC, vinkla commented
Thanks!